### PR TITLE
Reputation vs. Badge

### PR DESCRIPTION
**Pull request by Xyzzy-design**
Please take a look at this file. I am not sure whether it works or not.

### CODE REVIEW

**Comment by it176131** [comment]
Copy/pasting my reply on LinkedIn:

> You figured it out! I see the PR. Would you be willing to create a notebooks/ directory and put your notebook in there and then re-push? We can use that to hold all the .ipynb files

**Comment by it176131** [comment]
Something I noticed in your notebook was the comparison of "Badges in general" to Reputation. Does the API provide a difference between a "Tag Badge" and a "non-Tag Badge"?

**Review by it176131 — COMMENTED** [review]
Something I noticed in your notebook was the comparison of "Badges in general" to Reputation. Does the API provide a difference between a "Tag Badge" and a "non-Tag Badge"?

**Comment by Xyzzy-design** [comment]
> 

Done.

**Comment by Xyzzy-design** [comment]
I didn't find the "non-Tag Badge" yet. I am still exploring the API for extracting more information.

**Review by it176131 — COMMENTED** [review]
Gonna remove this one as it's an empty file.

**Review by it176131 — APPROVED** [review]
# Notes for future iterations
___
Need a way to differentiate between *tag badges* and *non-tag* badges. 

e.g. [`python`](https://stackoverflow.com/help/badges/267/python) is a *tag* badge, but [`Autobiographer`](https://stackoverflow.com/help/badges/9/autobiographer) is a *non-tag* badge.

[Types of badges](https://stackoverflow.com/help/badges):
- Question Badges
- Answer Badges
- Participation Badges
- Tag Badges
- Moderation Badges
- Other Badges
- Retired Badges

**Pull request merged**
